FLAGS = {
    "afeganistao": "https://flagcdn.com/w320/af.png",
    "africa do sul": "https://flagcdn.com/w320/za.png",
    "albania": "https://flagcdn.com/w320/al.png",
    "alemanha": "https://flagcdn.com/w320/de.png",
    "andorra": "https://flagcdn.com/w320/ad.png",
    "angola": "https://flagcdn.com/w320/ao.png",
    "antigua e barbuda": "https://flagcdn.com/w320/ag.png",
    "arabia saudita": "https://flagcdn.com/w320/sa.png",
    "argelia": "https://flagcdn.com/w320/dz.png",
    "argentina": "https://flagcdn.com/w320/ar.png",
    "armenia": "https://flagcdn.com/w320/am.png",
    "australia": "https://flagcdn.com/w320/au.png",
    "austria": "https://flagcdn.com/w320/at.png",
    "azerbaijao": "https://flagcdn.com/w320/az.png",
    "bahamas": "https://flagcdn.com/w320/bs.png",
    "bangladesh": "https://flagcdn.com/w320/bd.png",
    "barbados": "https://flagcdn.com/w320/bb.png",
    "barein": "https://flagcdn.com/w320/bh.png",
    "belgica": "https://flagcdn.com/w320/be.png",
    "belize": "https://flagcdn.com/w320/bz.png",
    "benim": "https://flagcdn.com/w320/bj.png",
    "bielorrussia": "https://flagcdn.com/w320/by.png",
    "bolivia": "https://flagcdn.com/w320/bo.png",
    "bosnia e herzegovina": "https://flagcdn.com/w320/ba.png",
    "botsuana": "https://flagcdn.com/w320/bw.png",
    "brasil": "https://flagcdn.com/w320/br.png",
    "brunei": "https://flagcdn.com/w320/bn.png",
    "bulgaria": "https://flagcdn.com/w320/bg.png",
    "burkina faso": "https://flagcdn.com/w320/bf.png",
    "burundi": "https://flagcdn.com/w320/bi.png",
    "butao": "https://flagcdn.com/w320/bt.png",
    "cabo verde": "https://flagcdn.com/w320/cv.png",
    "camaroes": "https://flagcdn.com/w320/cm.png",
    "camboja": "https://flagcdn.com/w320/kh.png",
    "canada": "https://flagcdn.com/w320/ca.png",
    "catar": "https://flagcdn.com/w320/qa.png",
    "cazaquistao": "https://flagcdn.com/w320/kz.png",
    "chade": "https://flagcdn.com/w320/td.png",
    "chile": "https://flagcdn.com/w320/cl.png",
    "china": "https://flagcdn.com/w320/cn.png",
    "chipre": "https://flagcdn.com/w320/cy.png",
    "colombia": "https://flagcdn.com/w320/co.png",
    "comores": "https://flagcdn.com/w320/km.png",
    "congo": "https://flagcdn.com/w320/cg.png",
    "coreia do norte": "https://flagcdn.com/w320/kp.png",
    "coreia do sul": "https://flagcdn.com/w320/kr.png",
    "costa do marfim": "https://flagcdn.com/w320/ci.png",
    "costa rica": "https://flagcdn.com/w320/cr.png",
    "croacia": "https://flagcdn.com/w320/hr.png",
    "cuba": "https://flagcdn.com/w320/cu.png",
    "dinamarca": "https://flagcdn.com/w320/dk.png",
    "djibuti": "https://flagcdn.com/w320/dj.png",
    "dominica": "https://flagcdn.com/w320/dm.png",
    "egito": "https://flagcdn.com/w320/eg.png",
    "el salvador": "https://flagcdn.com/w320/sv.png",
    "emirados arabes unidos": "https://flagcdn.com/w320/ae.png",
    "equador": "https://flagcdn.com/w320/ec.png",
    "eritreia": "https://flagcdn.com/w320/er.png",
    "eslovaquia": "https://flagcdn.com/w320/sk.png",
    "eslovenia": "https://flagcdn.com/w320/si.png",
    "espanha": "https://flagcdn.com/w320/es.png",
    "estados unidos": "https://flagcdn.com/w320/us.png",
    "estonia": "https://flagcdn.com/w320/ee.png",
    "etiopia": "https://flagcdn.com/w320/et.png",
    "fiji": "https://flagcdn.com/w320/fj.png",
    "filipinas": "https://flagcdn.com/w320/ph.png",
    "finlandia": "https://flagcdn.com/w320/fi.png",
    "franca": "https://flagcdn.com/w320/fr.png",
    "gabao": "https://flagcdn.com/w320/ga.png",
    "gambia": "https://flagcdn.com/w320/gm.png",
    "gana": "https://flagcdn.com/w320/gh.png",
    "georgia": "https://flagcdn.com/w320/ge.png",
    "granada": "https://flagcdn.com/w320/gd.png",
    "grecia": "https://flagcdn.com/w320/gr.png",
    "guatemala": "https://flagcdn.com/w320/gt.png",
    "guiana": "https://flagcdn.com/w320/gy.png",
    "guine": "https://flagcdn.com/w320/gn.png",
    "guine equatorial": "https://flagcdn.com/w320/gq.png",
    "guine-bissau": "https://flagcdn.com/w320/gw.png",
    "haiti": "https://flagcdn.com/w320/ht.png",
    "holanda": "https://flagcdn.com/w320/nl.png",
    "honduras": "https://flagcdn.com/w320/hn.png",
    "hungria": "https://flagcdn.com/w320/hu.png",
    "iemen": "https://flagcdn.com/w320/ye.png",
    "ilhas marshall": "https://flagcdn.com/w320/mh.png",
    "ilhas salomao": "https://flagcdn.com/w320/sb.png",
    "india": "https://flagcdn.com/w320/in.png",
    "indonesia": "https://flagcdn.com/w320/id.png",
    "ira": "https://flagcdn.com/w320/ir.png",
    "iraque": "https://flagcdn.com/w320/iq.png",
    "irlanda": "https://flagcdn.com/w320/ie.png",
    "islandia": "https://flagcdn.com/w320/is.png",
    "israel": "https://flagcdn.com/w320/il.png",
    "italia": "https://flagcdn.com/w320/it.png",
    "jamaica": "https://flagcdn.com/w320/jm.png",
    "japao": "https://flagcdn.com/w320/jp.png",
    "jordania": "https://flagcdn.com/w320/jo.png",
    "kiribati": "https://flagcdn.com/w320/ki.png",
    "kuwait": "https://flagcdn.com/w320/kw.png",
    "laos": "https://flagcdn.com/w320/la.png",
    "lesoto": "https://flagcdn.com/w320/ls.png",
    "letonia": "https://flagcdn.com/w320/lv.png",
    "libano": "https://flagcdn.com/w320/lb.png",
    "liberia": "https://flagcdn.com/w320/lr.png",
    "libia": "https://flagcdn.com/w320/ly.png",
    "liechtenstein": "https://flagcdn.com/w320/li.png",
    "lituania": "https://flagcdn.com/w320/lt.png",
    "luxemburgo": "https://flagcdn.com/w320/lu.png",
    "macedonia do norte": "https://flagcdn.com/w320/mk.png",
    "madagascar": "https://flagcdn.com/w320/mg.png",
    "malasia": "https://flagcdn.com/w320/my.png",
    "malaui": "https://flagcdn.com/w320/mw.png",
    "maldivas": "https://flagcdn.com/w320/mv.png",
    "mali": "https://flagcdn.com/w320/ml.png",
    "malta": "https://flagcdn.com/w320/mt.png",
    "marrocos": "https://flagcdn.com/w320/ma.png",
    "mauricio": "https://flagcdn.com/w320/mu.png",
    "mauritania": "https://flagcdn.com/w320/mr.png",
    "mexico": "https://flagcdn.com/w320/mx.png",
    "micronesia": "https://flagcdn.com/w320/fm.png",
    "mocambique": "https://flagcdn.com/w320/mz.png",
    "moldavia": "https://flagcdn.com/w320/md.png",
    "monaco": "https://flagcdn.com/w320/mc.png",
    "mongolia": "https://flagcdn.com/w320/mn.png",
    "montenegro": "https://flagcdn.com/w320/me.png",
    "myanmar": "https://flagcdn.com/w320/mm.png",
    "namibia": "https://flagcdn.com/w320/na.png",
    "nauru": "https://flagcdn.com/w320/nr.png",
    "nepal": "https://flagcdn.com/w320/np.png",
    "nicaragua": "https://flagcdn.com/w320/ni.png",
    "niger": "https://flagcdn.com/w320/ne.png",
    "nigeria": "https://flagcdn.com/w320/ng.png",
    "noruega": "https://flagcdn.com/w320/no.png",
    "nova zelandia": "https://flagcdn.com/w320/nz.png",
    "oma": "https://flagcdn.com/w320/om.png",
    "paises baixos": "https://flagcdn.com/w320/nl.png",
    "palau": "https://flagcdn.com/w320/pw.png",
    "panama": "https://flagcdn.com/w320/pa.png",
    "papua nova guine": "https://flagcdn.com/w320/pg.png",
    "paquistao": "https://flagcdn.com/w320/pk.png",
    "paraguai": "https://flagcdn.com/w320/py.png",
    "peru": "https://flagcdn.com/w320/pe.png",
    "polonia": "https://flagcdn.com/w320/pl.png",
    "portugal": "https://flagcdn.com/w320/pt.png",
    "quenia": "https://flagcdn.com/w320/ke.png",
    "quirguistao": "https://flagcdn.com/w320/kg.png",
    "reino unido": "https://flagcdn.com/w320/gb.png",
    "republica centro-africana": "https://flagcdn.com/w320/cf.png",
    "republica checa": "https://flagcdn.com/w320/cz.png",
    "republica democratica do congo": "https://flagcdn.com/w320/cd.png",
    "republica dominicana": "https://flagcdn.com/w320/do.png",
    "romenia": "https://flagcdn.com/w320/ro.png",
    "ruanda": "https://flagcdn.com/w320/rw.png",
    "russia": "https://flagcdn.com/w320/ru.png",
    "samoa": "https://flagcdn.com/w320/ws.png",
    "santa lucia": "https://flagcdn.com/w320/lc.png",
    "sao cristovao e nevis": "https://flagcdn.com/w320/kn.png",
    "sao marino": "https://flagcdn.com/w320/sm.png",
    "sao tome e principe": "https://flagcdn.com/w320/st.png",
    "sao vicente e granadinas": "https://flagcdn.com/w320/vc.png",
    "seicheles": "https://flagcdn.com/w320/sc.png",
    "senegal": "https://flagcdn.com/w320/sn.png",
    "serra leoa": "https://flagcdn.com/w320/sl.png",
    "servia": "https://flagcdn.com/w320/rs.png",
    "cingapura": "https://flagcdn.com/w320/sg.png",
    "siria": "https://flagcdn.com/w320/sy.png",
    "somalia": "https://flagcdn.com/w320/so.png",
    "sri lanka": "https://flagcdn.com/w320/lk.png",
    "suazilandia": "https://flagcdn.com/w320/sz.png",
    "sudao": "https://flagcdn.com/w320/sd.png",
    "sudao do sul": "https://flagcdn.com/w320/ss.png",
    "uecia": "https://flagcdn.com/w320/se.png",
    "suica": "https://flagcdn.com/w320/ch.png",
    "suriname": "https://flagcdn.com/w320/sr.png",
    "tailandia": "https://flagcdn.com/w320/th.png",
    "tajiquistao": "https://flagcdn.com/w320/tj.png",
    "tanzania": "https://flagcdn.com/w320/tz.png",
    "timor-leste": "https://flagcdn.com/w320/tl.png",
    "togo": "https://flagcdn.com/w320/tg.png",
    "tonga": "https://flagcdn.com/w320/to.png",
    "trinidad e tobago": "https://flagcdn.com/w320/tt.png",
    "tunisia": "https://flagcdn.com/w320/tn.png",
    "turcomenistao": "https://flagcdn.com/w320/tm.png",
    "turquia": "https://flagcdn.com/w320/tr.png",
    "tuvalu": "https://flagcdn.com/w320/tv.png",
    "ucrania": "https://flagcdn.com/w320/ua.png",
    "uganda": "https://flagcdn.com/w320/ug.png",
    "uruguai": "https://flagcdn.com/w320/uy.png",
    "uzbequistao": "https://flagcdn.com/w320/uz.png",
    "vanuatu": "https://flagcdn.com/w320/vu.png",
    "vaticano": "https://flagcdn.com/w320/va.png",
    "venezuela": "https://flagcdn.com/w320/ve.png",
    "vietna": "https://flagcdn.com/w320/vn.png",
    "zambia": "https://flagcdn.com/w320/zm.png",
    "zimbabue": "https://flagcdn.com/w320/zw.png"
}