piadas = [
"Por que a galinha atravessou a rua? Para chegar do outro lado!",
"Qual é o cúmulo do azar? Ser atropelado por uma ambulância.",
"Por que o computador foi ao médico? Porque estava com vírus!",
"O que o zero disse para o oito? Belo cinto!",
"Por que o lápis foi para a aula de música? Para aprender a fazer dó.",
"O que o tomate foi fazer no banco? Tirar extrato.",
"Por que o cachorro entrou na igreja? Porque ele era um pastor alemão.",
"Como se chama um boomerang que não volta? Um pedaço de pau.",
"O que o pato disse para a pata? Vem quá!",
"Por que a vaca foi para o espaço? Para ver a Via Láctea.",
"O que o pen drive falou para o computador? Me dá uma entrada?",
"Por que o peixe não gosta de jogar bola? Porque tem medo da rede.",
"O que a minhoca falou para a outra? Vou dar uma volta no quarteirão.",
"Por que a abelha sempre sabe o que fazer? Porque ela é BEE inteligente.",
"Como o elétron atende o telefone? Próton!",
"Por que o estudante levou uma escada para a escola? Para alcançar o alto nível.",
"Por que a bicicleta caiu? Porque estava sem apoio.",
"Como o café ficou famoso? Ele foi expresso na mídia.",
"O que a impressora disse para o papel? Isso vai ser impressão sua!",
"Por que o relógio sempre vence a corrida? Porque ele está adiantado.",
"O que o mar falou para a praia? Nada, só deu uma onda.",
"Por que o livro foi ao médico? Porque tinha muitas páginas amarelas.",
"Por que o astronauta levou um lápis para o espaço? Porque a caneta não funcionava.",
"Qual é o carro favorito do cachorro? O Fusca-late.",
"O que o pneu disse para o carro? Estou cansado!",
"Por que o telefone visitou o psicólogo? Porque tinha muitas ligações perdidas.",
"Por que o sapato foi ao médico? Porque estava apertado.",
"O que o milho falou para o milharal? Estou espiga-do!",
"Qual é o peixe mais inteligente? O bacalhau, porque vive na água salgada.",
"Por que o sol nunca vai para a faculdade? Porque ele já é um astro.",
"Como o papel se comunica? Pelo papel-fone.",
"Por que o sorvete não foi à aula? Porque derreteu.",
"O que a geladeira falou para o fogão? Tá calor aí, né?",
"Qual é a planta que fala? A samambaia: ""samambaia bem?""",
"Por que a caneta foi presa? Porque cometeu um rabisco.",
"O que a nuvem disse para a outra? Vamos dar uma volta, tá chovendo aqui.",
"Qual o animal mais antigo? A zebra, porque está em preto e branco.",
"Por que a pizza queria ir ao médico? Porque estava sentindo muita massa.",
"Como o livro pede comida? Pelo capítulo delivery.",
"Por que o banco foi preso? Porque guardava muitos segredos.",
"O que o vento disse para a árvore? Segura essa folha aí!",
"Por que o coelho não gosta de fila? Porque ele é muito apressado.",
"Como se despede um químico? Ácido prazer!",
"O que o elétrico disse para o fio? Você é muito ligado.",
"Por que o bebê não usou o computador? Porque ele ainda era muito pequeno para ""digitar"".",
"O que o sol disse para a lua? Você é tão iluminada!",
"Por que o papel não pode ir ao baile? Porque era muito quadrado.",
"Por que o bolo foi preso? Porque bateu a clara.",
"O que o celular disse para o carregador? Você me completa.",
"Por que o gato não gosta de computador? Porque tem medo do mouse!",
"Como o programador se despede? Até o próximo loop!",
"Por que o meteorologista sempre ganha no pôquer? Porque ele prevê tempestades.",
"Qual o cúmulo da rapidez? Tomar café e correr para o banheiro ao mesmo tempo.",
"O que o programador disse quando o código funcionou de primeira? Milagre.exe!",
"Por que o papel ficou amigo do lápis? Porque ele era muito ponta firme.",
"Como o servidor responde? Estou on!",
"Por que o celular foi para terapia? Porque estava com muita ansiedade de notificações.",
"O que o oceano faz quando está bravo? Onda.",
"Por que o panda é péssimo no futebol? Só faz panda-lhaço.",
"Qual o cúmulo da fome? Comer a sobremesa antes da refeição e ainda ficar faminto.",
"Por que o Wi‑Fi brigou com o roteador? Perdeu a conexão emocional.",
"Como o relógio pede silêncio? Tic‑tac, por favor.",
"Por que o foguete terminou o namoro? Precisava de espaço.",
"O que a cebola disse pro tomate? Não chora, não é drama!",
"Como o código flerta? Quer compilar comigo?",
"O que o café disse para o açúcar? Sem você eu fico amargo.",
"Por que o skeleton não luta? Porque não tem coragem.",
"Qual o cúmulo da curiosidade? Perguntar se é segredo e contar depois.",
"O que o dente falou para a gengiva? Estamos grudados para sempre.",
"Por que a TV nunca perde as chaves? Porque sempre tem controle.",
"Como o computador pede desculpas? Foi um bug emocional.",
"Por que o peixe entrou na igreja? Para dizer ""amém‑nho"".",
"Como o livro vai para a academia? Levando capítulos pesados.",
"O que o teclado falou para o mouse? Não clique comigo!",
"Por que o avião contou piadas? Para manter o humor nas alturas.",
"Como o professor de matemática faz churrasco? Com muita geometria da grelha.",
"Por que a lâmpada foi promovida? Porque tinha boas ideias.",
"O que o chocolate disse ao leite? Vamos derreter juntos!",
"Como o gamer agradece? Valeu, GG!",
"Por que o vento não tem amigos? Porque vive passando.",
"O que a nuvem virou quando cresceu? Tempestade.",
"Como o programador toma banho? Em modo debug.",
"Por que o tomate virou coach? Aprendeu a se extrair.",
"Como o código sai para caminhar? Em passos recursivos.",
"Por que o livro de história dormiu? Estava cheio de capítulos cansativos.",
"Como o hacker faz dieta? Corta os cookies.",
"O que o pão disse para a manteiga? Você me derrete.",
"Por que o relógio foi expulso? Causava muitos atrasos.",
"Como o disco rígido se declara? Guardo tudo de você no meu coração magnético.",
"Por que o banco nunca mente? Porque sempre tem saldo.",
"Como o sol elogia a lua? Você brilha até no escuro.",
"Por que o teclado foi preso? Ficou teclando demais.",
"Como o refrigerante escreve? Com gás‑ta tinta.",
"Por que o ônibus é filósofo? Vive fazendo paradas para pensar.",
"Como o gelado faz amizade? Com um gelo e risadas.",
"Por que o leite acordou cedo? Para não talhar os compromissos.",
]
